#!/usr/bin/env python3
"""
===============================================================================
build_statistics.py (Part 1)
===============================================================================

This script computes descriptive statistics from the radar cache generated by
build_radar_cache.py.

Unlike the original PNG archive, the cache contains one NumPy array per radar
timestamp already projected onto the CorrDiff grid (70 x 84), allowing the
entire historical archive to be processed efficiently.

The complete pipeline is divided into four implementation stages.

Part 1 implements:

    • configuration
    • logging
    • radar cache discovery
    • worker initialization
    • worker processing
    • accumulator data structures

Later parts will implement:

    Part 2
        - parallel processing
        - parquet generation

    Part 3
        - spatial climatology maps

    Part 4
        - global statistics
        - extreme event catalogue
        - JSON export

Author:
    Vinicius Gonçalves dos Santos

===============================================================================
"""

from __future__ import annotations

import json
import logging
import multiprocessing as mp
import os
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np
import pandas as pd
from tqdm import tqdm

from src.config.paths import RADAR_CACHE_DIR

# =============================================================================
# CONFIGURATION
# =============================================================================

OUTPUT_DIR = Path("datasets/radar_statistics")

SUMMARY_PARQUET = OUTPUT_DIR / "summary.parquet"

EXTREME_EVENTS = OUTPUT_DIR / "extreme_events.parquet"

GLOBAL_JSON = OUTPUT_DIR / "global_statistics.json"

MAP_MEAN = OUTPUT_DIR / "mean_grid.npy"

MAP_STD = OUTPUT_DIR / "std_grid.npy"

MAP_MAX = OUTPUT_DIR / "max_grid.npy"

MAP_ACCUM = OUTPUT_DIR / "accumulated_rain.npy"

MAP_OCCURRENCE = OUTPUT_DIR / "rain_occurrence.npy"

MAP_PROBABILITY = OUTPUT_DIR / "rain_probability.npy"

# -----------------------------------------------------

GRID_HEIGHT = 70

GRID_WIDTH = 84

RAIN_THRESHOLD = 0.0

PARQUET_BATCH_SIZE = 5000

MAX_WORKERS = max(1, mp.cpu_count() - 2)

# =============================================================================
# LOGGER
# =============================================================================


def setup_logger():

    logger = logging.getLogger("RadarStatistics")

    if logger.handlers:
        return logger

    logger.setLevel(logging.INFO)

    handler = logging.StreamHandler()

    formatter = logging.Formatter(
        "[%(asctime)s] [%(levelname)s] %(message)s"
    )

    handler.setFormatter(formatter)

    logger.addHandler(handler)

    return logger


logger = setup_logger()

# =============================================================================
# CACHE DISCOVERY
# =============================================================================


def discover_cache_files(cache_dir: Path):

    """
    Returns every cached radar grid (.npy).

    Files are sorted chronologically because their filenames follow

        YYYYMMDD_HHMM.npy

    Returns
    -------
    list(Path)
    """

    files = sorted(cache_dir.rglob("*.npy"))

    logger.info(
        "Radar cache files found: %d",
        len(files),
    )

    return files


# =============================================================================
# TIMESTAMP PARSER
# =============================================================================


def filename_to_timestamp(cache_file):
    """
    Converts cache filename to pandas.Timestamp.

    Supported format:

        YYYYMMDD_HH_MM.npy

    Example:

        20241231_23_58.npy
    """

    stem = cache_file.stem

    return pd.to_datetime(
        stem,
        format="%Y%m%d_%H_%M",
    )


# =============================================================================
# GLOBAL WORKER STATE
# =============================================================================

WORKER_CACHE = None

# =============================================================================
# WORKER INITIALIZER
# =============================================================================


def initialize_worker():

    """
    Executed exactly once for each worker process.

    Nothing heavy is loaded here because each worker simply reads .npy files.
    """

    global WORKER_CACHE

    WORKER_CACHE = True


# =============================================================================
# WORKER FUNCTION
# =============================================================================


def process_file(cache_file: Path):

    """
    Processes one cached radar image.

    Returns a lightweight dictionary containing all statistics required by the
    main process.

    Notes
    -----
    Spatial climatology maps are also accumulated here in order to minimize
    repeated passes over the dataset.
    """

    try:

        grid = np.load(cache_file)

    except Exception:

        return None

    valid = np.isfinite(grid)

    rain = valid & (grid > RAIN_THRESHOLD)

    rain_values = grid[rain]

    timestamp = filename_to_timestamp(cache_file)

    if rain_values.size == 0:

        summary = dict(

            timestamp=timestamp,

            rain_pixels=0,

            rain_fraction=0.0,

            mean=0.0,

            std=0.0,

            maximum=0.0,

            volume=0.0,

            p50=0.0,

            p90=0.0,

            p95=0.0,

            p99=0.0,
        )

    else:

        summary = dict(

            timestamp=timestamp,

            rain_pixels=int(rain.sum()),

            rain_fraction=float(rain.mean()),

            mean=float(rain_values.mean()),

            std=float(rain_values.std()),

            maximum=float(rain_values.max()),

            volume=float(rain_values.sum()),

            p50=float(np.percentile(rain_values, 50)),

            p90=float(np.percentile(rain_values, 90)),

            p95=float(np.percentile(rain_values, 95)),

            p99=float(np.percentile(rain_values, 99)),
        )

    #
    # Everything below is required later to build
    # climatological spatial maps.
    #

    return {

        "summary": summary,

        "grid_sum": np.nan_to_num(grid),

        "grid_sq_sum": np.nan_to_num(grid ** 2),

        "grid_max": np.nan_to_num(grid),

        "grid_occurrence": rain.astype(np.uint8),

        "grid_accum": np.nan_to_num(grid),

        "valid": valid.astype(np.uint8),
    }


# =============================================================================
# GLOBAL ACCUMULATORS
# =============================================================================


class StatisticsAccumulator:
    """
    Holds every accumulator required to build the climatological products.

    These arrays remain in memory during the entire execution.

    Memory footprint is negligible:

        70 x 84 x float64
    """

    def __init__(self):

        shape = (GRID_HEIGHT, GRID_WIDTH)

        self.grid_sum = np.zeros(shape, dtype=np.float64)

        self.grid_sq_sum = np.zeros(shape, dtype=np.float64)

        self.grid_max = np.zeros(shape, dtype=np.float32)

        self.grid_occurrence = np.zeros(
            shape,
            dtype=np.uint32,
        )

        self.grid_accum = np.zeros(
            shape,
            dtype=np.float64,
        )

        self.valid_count = np.zeros(
            shape,
            dtype=np.uint32,
        )

        #
        # Global statistics
        #

        self.total_images = 0

        self.failed_images = 0

        self.global_sum = 0.0

        self.global_sq_sum = 0.0

        self.global_pixels = 0

        self.global_max = 0.0

        #
        # Summary dataframe buffer.
        #

        self.summary_buffer = []

        #
        # Extreme events.
        #

        self.extreme_events = []
        
# =============================================================================
# PART 2
#
# Parallel processing engine
# Incremental Parquet writer
# Global accumulators
# =============================================================================

import pyarrow as pa
import pyarrow.parquet as pq


# =============================================================================
# PARQUET WRITER
# =============================================================================


class SummaryWriter:
    """
    Incrementally writes summary statistics to Parquet.

    The dataframe never stays completely in memory.
    """

    def __init__(self, output_file: Path):

        self.output_file = output_file

        self.writer = None

    def append(self, rows):

        if len(rows) == 0:
            return

        df = pd.DataFrame(rows)

        table = pa.Table.from_pandas(df)

        if self.writer is None:

            self.writer = pq.ParquetWriter(
                self.output_file,
                table.schema,
                compression="zstd",
            )

        self.writer.write_table(table)

    def close(self):

        if self.writer is not None:
            self.writer.close()


# =============================================================================
# UPDATE ACCUMULATORS
# =============================================================================


def update_accumulators(
    accumulator: StatisticsAccumulator,
    result: dict,
):

    """
    Update every global accumulator from one processed image.
    """

    accumulator.total_images += 1

    # ------------------------------------------------------------
    # dataframe row
    # ------------------------------------------------------------

    summary = result["summary"]

    accumulator.summary_buffer.append(summary)

    # ------------------------------------------------------------
    # spatial maps
    # ------------------------------------------------------------

    accumulator.grid_sum += result["grid_sum"]

    accumulator.grid_sq_sum += result["grid_sq_sum"]

    accumulator.grid_accum += result["grid_accum"]

    accumulator.grid_occurrence += result["grid_occurrence"]

    accumulator.valid_count += result["valid"]

    accumulator.grid_max = np.maximum(
        accumulator.grid_max,
        result["grid_max"],
    )

    # ------------------------------------------------------------
    # global statistics
    # ------------------------------------------------------------

    values = result["grid_accum"]

    mask = result["valid"].astype(bool)

    valid_values = values[mask]

    accumulator.global_sum += valid_values.sum()

    accumulator.global_sq_sum += (valid_values ** 2).sum()

    accumulator.global_pixels += valid_values.size

    if valid_values.size > 0:

        accumulator.global_max = max(

            accumulator.global_max,

            float(valid_values.max()),

        )

    # ------------------------------------------------------------
    # extreme event catalogue
    # ------------------------------------------------------------

    accumulator.extreme_events.append(

        {

            "timestamp": summary["timestamp"],

            "max_reflectivity": summary["maximum"],

            "rain_pixels": summary["rain_pixels"],

            "rain_fraction": summary["rain_fraction"],

            "volume": summary["volume"],

            "mean": summary["mean"],

        }

    )


# =============================================================================
# FLUSH SUMMARY BUFFER
# =============================================================================


def flush_summary_buffer(
    accumulator: StatisticsAccumulator,
    writer: SummaryWriter,
):

    """
    Writes buffered rows to parquet.
    """

    if len(accumulator.summary_buffer) == 0:
        return

    writer.append(accumulator.summary_buffer)

    accumulator.summary_buffer.clear()


# =============================================================================
# MAIN PROCESSING LOOP
# =============================================================================


def process_cache():

    """
    Main processing routine.

    Returns
    -------
    StatisticsAccumulator
    """

    OUTPUT_DIR.mkdir(
        exist_ok=True,
        parents=True,
    )

    logger.info("Scanning cache directory...")

    cache_files = discover_cache_files(
        Path(RADAR_CACHE_DIR)
    )

    logger.info(
    f"Radar cache files found: {len(cache_files):,}"
)

    accumulator = StatisticsAccumulator()

    writer = SummaryWriter(
        SUMMARY_PARQUET,
    )

    logger.info(
        "Starting parallel processing..."
    )

    with ProcessPoolExecutor(

        max_workers=MAX_WORKERS,

        initializer=initialize_worker,

    ) as executor:

        iterator = executor.map(

            process_file,

            cache_files,

            chunksize=250,

        )

        for result in tqdm(

            iterator,

            total=len(cache_files),

            desc="Processing radar cache",

        ):

            if result is None:

                accumulator.failed_images += 1

                continue

            update_accumulators(
                accumulator,
                result,
            )

            if (

                len(
                    accumulator.summary_buffer
                )

                >= PARQUET_BATCH_SIZE

            ):

                flush_summary_buffer(
                    accumulator,
                    writer,
                )

    logger.info(
        "Writing remaining rows..."
    )

    flush_summary_buffer(
        accumulator,
        writer,
    )

    writer.close()

    logger.info("Summary parquet completed.")

    logger.info(
        "Images processed : %d",
        accumulator.total_images,
    )

    logger.info(
        "Images failed    : %d",
        accumulator.failed_images,
    )

    return accumulator

# =============================================================================
# PART 3
#
# Spatial climatology generation
#
# This stage converts the accumulators into climatological products that are
# later used by the exploratory notebooks.
#
# Generated products
#
#   mean_grid.npy
#   std_grid.npy
#   max_grid.npy
#   accumulated_rain.npy
#   rain_occurrence.npy
#   rain_probability.npy
#
# =============================================================================


def generate_spatial_products(
    accumulator: StatisticsAccumulator,
):
    """
    Generates all spatial climatology products.

    Parameters
    ----------
    accumulator : StatisticsAccumulator

    Returns
    -------
    dict
        Dictionary containing every generated map.
    """

    logger.info("Generating spatial climatology maps...")

    valid = accumulator.valid_count > 0

    mean_grid = np.zeros_like(
        accumulator.grid_sum,
        dtype=np.float32,
    )

    std_grid = np.zeros_like(
        accumulator.grid_sum,
        dtype=np.float32,
    )

    rain_probability = np.zeros_like(
        accumulator.grid_sum,
        dtype=np.float32,
    )

    #
    # ------------------------------------------------------------------
    # Mean
    # ------------------------------------------------------------------
    #

    mean_grid[valid] = (

        accumulator.grid_sum[valid]

        /

        accumulator.valid_count[valid]

    )

    #
    # ------------------------------------------------------------------
    # Variance
    # ------------------------------------------------------------------
    #

    variance = np.zeros_like(
        accumulator.grid_sum,
        dtype=np.float64,
    )

    variance[valid] = (

        accumulator.grid_sq_sum[valid]

        /

        accumulator.valid_count[valid]

    ) - (

        mean_grid[valid] ** 2

    )

    variance = np.maximum(
        variance,
        0,
    )

    std_grid[valid] = np.sqrt(
        variance[valid]
    )

    #
    # ------------------------------------------------------------------
    # Rain probability
    # ------------------------------------------------------------------
    #

    rain_probability[valid] = (

        accumulator.grid_occurrence[valid]

        /

        accumulator.valid_count[valid]

    )

    #
    # ------------------------------------------------------------------
    # Max grid
    # ------------------------------------------------------------------
    #

    max_grid = accumulator.grid_max.astype(
        np.float32
    )

    #
    # ------------------------------------------------------------------
    # Accumulated rainfall
    # ------------------------------------------------------------------
    #

    accumulated_grid = accumulator.grid_accum.astype(
        np.float32
    )

    #
    # ------------------------------------------------------------------
    # Rain occurrence
    # ------------------------------------------------------------------
    #

    occurrence_grid = accumulator.grid_occurrence.astype(
        np.uint32
    )

    #
    # ------------------------------------------------------------------
    # Save every product
    # ------------------------------------------------------------------
    #

    logger.info("Saving mean grid...")

    np.save(
        MAP_MEAN,
        mean_grid,
    )

    logger.info("Saving std grid...")

    np.save(
        MAP_STD,
        std_grid,
    )

    logger.info("Saving max grid...")

    np.save(
        MAP_MAX,
        max_grid,
    )

    logger.info("Saving accumulated rainfall grid...")

    np.save(
        MAP_ACCUM,
        accumulated_grid,
    )

    logger.info("Saving rain occurrence grid...")

    np.save(
        MAP_OCCURRENCE,
        occurrence_grid,
    )

    logger.info("Saving rain probability grid...")

    np.save(
        MAP_PROBABILITY,
        rain_probability,
    )

    logger.info("Spatial products successfully generated.")

    return {

        "mean": mean_grid,

        "std": std_grid,

        "max": max_grid,

        "accumulated": accumulated_grid,

        "occurrence": occurrence_grid,

        "probability": rain_probability,

    }


# =============================================================================
# PRODUCT SUMMARY
# =============================================================================


def print_spatial_summary(products):
    """
    Prints a summary of every generated climatological map.
    """

    logger.info("")

    logger.info("===================================================")
    logger.info("Spatial climatology summary")
    logger.info("===================================================")

    logger.info(

        "Mean rainfall range : %.3f  %.3f",

        products["mean"].min(),

        products["mean"].max(),

    )

    logger.info(

        "Std rainfall range  : %.3f  %.3f",

        products["std"].min(),

        products["std"].max(),

    )

    logger.info(

        "Maximum rainfall    : %.3f",

        products["max"].max(),

    )

    logger.info(

        "Rain probability    : %.5f  %.5f",

        products["probability"].min(),

        products["probability"].max(),

    )

    logger.info(

        "Accumulated rainfall: %.3f",

        products["accumulated"].sum(),

    )

    logger.info("===================================================")
    
# =============================================================================
# PART 4
#
# Final products
#
#   • global_statistics.json
#   • extreme_events.parquet
#   • execution report
#   • main()
#
# =============================================================================

import time


# =============================================================================
# GLOBAL STATISTICS
# =============================================================================


def generate_global_statistics(
    accumulator: StatisticsAccumulator,
):

    logger.info("Generating global statistics...")

    mean = (

        accumulator.global_sum

        /

        accumulator.global_pixels

    )

    variance = (

        accumulator.global_sq_sum

        /

        accumulator.global_pixels

    ) - mean ** 2

    variance = max(
        variance,
        0,
    )

    std = np.sqrt(variance)

    global_stats = {

        "total_images": int(
            accumulator.total_images
        ),

        "failed_images": int(
            accumulator.failed_images
        ),

        "valid_pixels": int(
            accumulator.global_pixels
        ),

        "global_mean": float(mean),

        "global_std": float(std),

        "global_max": float(
            accumulator.global_max
        ),

    }

    with open(
        GLOBAL_JSON,
        "w",
    ) as f:

        json.dump(
            global_stats,
            f,
            indent=4,
        )

    logger.info(
        "Global statistics written to %s",
        GLOBAL_JSON,
    )

    return global_stats


# =============================================================================
# EXTREME EVENT CATALOG
# =============================================================================


def build_extreme_event_catalog(
    accumulator: StatisticsAccumulator,
):

    logger.info(
        "Generating extreme event catalog..."
    )

    df = pd.DataFrame(
        accumulator.extreme_events
    )

    #
    # Composite severity score.
    #
    # The weights may be tuned later.
    #

    df["event_rank"] = (

        0.50 * df["max_reflectivity"]

        +

        0.30 * df["rain_fraction"]

        +

        0.20 * np.log1p(df["volume"])

    )

    df = df.sort_values(

        "event_rank",

        ascending=False,

    )

    df.reset_index(
        drop=True,
        inplace=True,
    )

    df.to_parquet(

        EXTREME_EVENTS,

        compression="zstd",

        index=False,

    )

    logger.info(

        "Extreme event catalog written."

    )

    logger.info(

        "Top event score : %.2f",

        df.iloc[0]["event_rank"],

    )

    return df


# =============================================================================
# EXECUTION REPORT
# =============================================================================


def print_execution_report(
    global_statistics,
    products,
    extreme_catalog,
):

    logger.info("")

    logger.info(
        "=" * 70
    )

    logger.info(
        "RADAR STATISTICS SUCCESSFULLY GENERATED"
    )

    logger.info(
        "=" * 70
    )

    logger.info(

        "Images processed : %d",

        global_statistics["total_images"],

    )

    logger.info(

        "Failed images    : %d",

        global_statistics["failed_images"],

    )

    logger.info(

        "Mean rainfall    : %.3f",

        global_statistics["global_mean"],

    )

    logger.info(

        "Std rainfall     : %.3f",

        global_statistics["global_std"],

    )

    logger.info(

        "Maximum rainfall : %.3f",

        global_statistics["global_max"],

    )

    logger.info("")

    logger.info(
        "Generated products:"
    )

    logger.info(
        "    summary.parquet"
    )

    logger.info(
        "    global_statistics.json"
    )

    logger.info(
        "    extreme_events.parquet"
    )

    logger.info(
        "    mean_grid.npy"
    )

    logger.info(
        "    std_grid.npy"
    )

    logger.info(
        "    max_grid.npy"
    )

    logger.info(
        "    accumulated_rain.npy"
    )

    logger.info(
        "    rain_occurrence.npy"
    )

    logger.info(
        "    rain_probability.npy"
    )

    logger.info("")

    logger.info(
        "Top 10 historical events"
    )

    logger.info(
        "-" * 70
    )

    print(

        extreme_catalog.head(10)[

            [

                "timestamp",

                "max_reflectivity",

                "rain_fraction",

                "volume",

                "event_rank",

            ]

        ]

    )

    logger.info(
        "=" * 70
    )


# =============================================================================
# MAIN
# =============================================================================


def main():

    start = time.time()

    logger.info("")

    logger.info(
        "=" * 70
    )

    logger.info(
        "Radar Statistics Builder"
    )

    logger.info(
        "=" * 70
    )

    #
    # -----------------------------------------------------------------
    # Part 2
    #
    # Process every cached radar image.
    # -----------------------------------------------------------------
    #

    accumulator = process_cache()

    #
    # -----------------------------------------------------------------
    # Part 3
    #
    # Generate climatological maps.
    # -----------------------------------------------------------------
    #

    spatial_products = generate_spatial_products(
        accumulator
    )

    print_spatial_summary(
        spatial_products
    )

    #
    # -----------------------------------------------------------------
    # Global statistics.
    # -----------------------------------------------------------------
    #

    global_statistics = generate_global_statistics(
        accumulator
    )

    #
    # -----------------------------------------------------------------
    # Extreme event catalogue.
    # -----------------------------------------------------------------
    #

    extreme_catalog = build_extreme_event_catalog(
        accumulator
    )

    #
    # -----------------------------------------------------------------
    # Final report.
    # -----------------------------------------------------------------
    #

    print_execution_report(

        global_statistics,

        spatial_products,

        extreme_catalog,

    )

    elapsed = (

        time.time()

        - start

    )

    logger.info(

        "Execution time: %.2f hours",

        elapsed / 3600,

    )


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":

    main()