#!/usr/bin/env python3
"""
Phase 18 - install RioNowcast custom CorrDiff smoke configs into a real
NVIDIA PhysicsNeMo CorrDiff checkout.

Only NEW files are added:
- conf/config_training_rionowcast_C00_regression_smoke.yaml
- conf/config_training_rionowcast_C00_diffusion_smoke.yaml
- conf/config_training_rionowcast_C07_regression_smoke.yaml
- conf/config_training_rionowcast_C07_diffusion_smoke.yaml

No NVIDIA source file is patched.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


PHASE_VERSION = "phase18-nvidia-corrdiff-native-integration-v1-smoke-only"


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--corrdiff-dir", type=Path, required=True)
    p.add_argument(
        "--adapter-path",
        type=Path,
        required=True,
        help="Absolute or resolvable path to rionowcast_corrdiff_dataset.py",
    )
    p.add_argument(
        "--dataset-dir",
        type=Path,
        default=Path("datasets/corrdiff_2011_2024"),
    )
    p.add_argument(
        "--phase15-dir",
        type=Path,
        default=Path("analysis_outputs/15_formal_splits"),
    )
    p.add_argument(
        "--phase17-dir",
        type=Path,
        default=Path("analysis_outputs/17_conditioning_ablations"),
    )
    p.add_argument(
        "--stats-dir",
        type=Path,
        default=Path(
            "analysis_outputs/18_nvidia_integration/conditioning_stats"
        ),
    )
    p.add_argument(
        "--smoke-output-root",
        type=Path,
        default=Path(
            "analysis_outputs/18_nvidia_integration/native_smoke"
        ),
    )
    p.add_argument("--training-duration", type=int, default=64)
    p.add_argument("--batch-size-per-gpu", type=int, default=2)
    p.add_argument("--overwrite", action="store_true")
    return p.parse_args()


def q(path: Path) -> str:
    # YAML plain scalars are awkward with ':' or '#'; JSON quoting is YAML-safe.
    return json.dumps(str(path.expanduser().resolve()))


def config_text(
    *,
    stage: str,
    experiment_id: str,
    adapter_path: Path,
    data_path: Path,
    train_idx: Path,
    val_idx: Path,
    ablation_matrix: Path,
    stats_path: Path,
    output_dir: Path,
    training_duration: int,
    batch_size: int,
) -> str:
    if stage not in {"regression", "diffusion"}:
        raise ValueError(stage)

    job = f"rionowcast_{experiment_id}_{stage}_smoke"

    diffusion_io = ""
    if stage == "diffusion":
        diffusion_io = (
            "\n  io:\n"
            "    print_progress_freq: 1\n"
            "    regression_checkpoint_path: ${oc.env:CORRDIFF_REGRESSION_CKPT}\n"
        )
    else:
        diffusion_io = (
            "\n  io:\n"
            "    print_progress_freq: 1\n"
        )

    return f"""# Auto-generated by CorrDiff Phase 18
# Smoke only: train/validation, mini model, tiny sample budget.
hydra:
  job:
    chdir: false
    name: {job}
  run:
    dir: {q(output_dir)}
  searchpath:
    - pkg://conf/base

defaults:
  - dataset: custom
  - model: {stage}
  - model_size: mini
  - training: ${{model}}

dataset:
  type: {q(adapter_path)}::RioNowcastCorrDiffDataset
  data_path: {q(data_path)}
  split_indices_path: {q(train_idx)}
  ablation_matrix_path: {q(ablation_matrix)}
  experiment_id: {experiment_id}
  stats_path: {q(stats_path)}
  split_name: train
  allow_locked_split: false
  coordinate_mode: relative_patch
  grid_spacing_km: 2.0

validation:
  split_indices_path: {q(val_idx)}
  split_name: validation
  allow_locked_split: false

training:
  hp:
    training_duration: {training_duration}
    batch_size_per_gpu: {batch_size}
    total_batch_size: {batch_size}
{diffusion_io}
wandb:
  mode: disabled
  results_dir: {q(output_dir / "wandb")}
  watch_model: false
"""


def main():
    args = parse_args()

    corrdiff = args.corrdiff_dir.expanduser().resolve()
    conf_dir = corrdiff / "conf"
    if not (corrdiff / "train.py").exists():
        raise FileNotFoundError(
            f"{corrdiff}/train.py not found"
        )
    if not conf_dir.exists():
        raise FileNotFoundError(conf_dir)

    adapter = args.adapter_path.expanduser().resolve()
    data = (args.dataset_dir / "train.zarr").expanduser().resolve()
    train_idx = (
        args.phase15_dir / "train_patch_indices.npy"
    ).expanduser().resolve()
    val_idx = (
        args.phase15_dir / "validation_patch_indices.npy"
    ).expanduser().resolve()
    ablation = (
        args.phase17_dir / "ablation_matrix.json"
    ).expanduser().resolve()

    required = [adapter, data, train_idx, val_idx, ablation]
    for path in required:
        if not path.exists():
            raise FileNotFoundError(path)

    emitted = []

    for experiment_id in ["C00", "C07"]:
        stats = (
            args.stats_dir / f"{experiment_id}.npz"
        ).expanduser().resolve()
        if not stats.exists():
            raise FileNotFoundError(stats)

        for stage in ["regression", "diffusion"]:
            filename = (
                f"config_training_rionowcast_"
                f"{experiment_id}_{stage}_smoke.yaml"
            )
            path = conf_dir / filename

            if path.exists() and not args.overwrite:
                raise FileExistsError(
                    f"{path} exists; use --overwrite"
                )

            output_dir = (
                args.smoke_output_root
                / f"{experiment_id}_{stage}"
            ).expanduser().resolve()

            path.write_text(
                config_text(
                    stage=stage,
                    experiment_id=experiment_id,
                    adapter_path=adapter,
                    data_path=data,
                    train_idx=train_idx,
                    val_idx=val_idx,
                    ablation_matrix=ablation,
                    stats_path=stats,
                    output_dir=output_dir,
                    training_duration=args.training_duration,
                    batch_size=args.batch_size_per_gpu,
                ),
                encoding="utf-8",
            )

            emitted.append(str(path))

    manifest = {
        "phase_version": PHASE_VERSION,
        "corrdiff_dir": str(corrdiff),
        "strategy": (
            "official custom dataset hook + new Hydra configs; "
            "no NVIDIA core-file modifications"
        ),
        "experiments_installed": ["C00", "C07"],
        "stages": ["regression", "diffusion"],
        "training_duration_samples": args.training_duration,
        "batch_size_per_gpu": args.batch_size_per_gpu,
        "configs": emitted,
        "tests_accessed": False,
        "locked_tests": [
            "test_primary",
            "test_stress_ood",
        ],
    }

    out = (
        args.smoke_output_root.parent
        / "phase18_install_manifest.json"
    ).expanduser().resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print(json.dumps(
        manifest,
        indent=2,
        ensure_ascii=False,
    ))


if __name__ == "__main__":
    main()
